import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Dict = Record<string, string>;

type Lang = 'en' | 'hi' | 'ur';

const en: Dict = {
  'common.theme': 'Theme',
  'common.english': 'English',
  'common.hindi': 'हिंदी',
  'common.urdu': 'اردو',
  'common.close': 'Close',
  'common.print_certificate': 'Print Certificate',
  'common.loading': 'Loading...',
  'common.cancel': 'Cancel',
  'common.submit': 'Submit',
  'common.view': 'View',
  'common.view_all': 'View All',
  'common.apply_leave': 'Apply for Leave',
  'common.details': 'View Details',

  // Table headers (generic)
  'table.assignment': 'Assignment',
  'table.due_date': 'Due Date',
  'table.action': 'Action',
  'table.due': 'Due',
  'table.attempts': 'Attempts',

  // Status
  'status.present': 'Present',
  'status.absent': 'Absent',
  'status.late': 'Late',
  'status.excused': 'Excused',
  'status.half_day': 'Half Day',

  // Timetable
  'timetable.break': 'Break',
  'timetable.lunch_break': 'Lunch Break',

  // Student Dashboard
  'student.dashboard.title': 'Student Dashboard',
  'student.dashboard.welcome': 'Welcome back, {name}! Stay on top of your studies.',
  'student.dashboard.attendance_rate': 'Attendance Rate',
  'student.dashboard.average_grade': 'Average Grade',
  'student.dashboard.pending': 'Pending',
  'student.dashboard.exams': 'Exams',
  'student.dashboard.done': 'Done',
  'student.dashboard.todays_classes': "Today's Classes",
  'student.dashboard.pending_assignments': 'Pending Assignments',
  'student.dashboard.recent_grades': 'Recent Grades',
  'student.dashboard.apply_leave': 'Apply for Leave',
  'student.dashboard.leave_type': 'Leave Type',
  'student.dashboard.sick_leave': 'Sick Leave',
  'student.dashboard.personal': 'Personal',
  'student.dashboard.family_emergency': 'Family Emergency',
  'student.dashboard.other': 'Other',
  'student.dashboard.start_date': 'Start Date',
  'student.dashboard.end_date': 'End Date',
  'student.dashboard.reason': 'Reason',
  'student.dashboard.leave_info': 'Your leave application will be sent to your parent for approval, then forwarded to admin.',
  'student.dashboard.submit_application': 'Submit Application',

  // Teacher Dashboard
  'teacher.dashboard.title': 'Teacher Dashboard',
  'teacher.dashboard.welcome': "Welcome, {name}! Ready for today's classes?",
  'teacher.dashboard.leave_balances': 'Leave Balances',
  'teacher.dashboard.apply_leave': 'Apply Leave',
  'teacher.dashboard.privilege': 'Privilege',
  'teacher.dashboard.sick': 'Sick',
  'teacher.dashboard.my_classes': 'My Classes',
  'teacher.dashboard.students': 'Students',
  'teacher.dashboard.assignments': 'Assignments',
  'teacher.dashboard.to_grade': 'To Grade',
  'teacher.dashboard.today': 'Today',
  'teacher.dashboard.attendance': 'Attendance',
  'teacher.dashboard.todays_schedule': "Today's Schedule",
  'teacher.dashboard.classes_count': 'Classes',
  'teacher.dashboard.quick_actions': 'Quick Actions',
  'teacher.dashboard.mark_attendance': 'Mark Attendance',
  'teacher.dashboard.create_assignment': 'Create Assignment',
  'teacher.dashboard.grade_submissions': 'Grade Submissions',
  'teacher.dashboard.send_announcement': 'Send Announcement',
  'teacher.dashboard.recent_submissions': 'Recent Submissions',
  'teacher.dashboard.start_class': 'Start Class',

  // Parent Dashboard
  'parent.dashboard.title': 'Parent Dashboard',
  'parent.dashboard.welcome': "Welcome, {name}! Track your children's progress.",
  'parent.dashboard.attendance': 'Attendance',
  'parent.dashboard.average_grade': 'Average Grade',
  'parent.dashboard.upcoming_exams': 'Upcoming Exams',
  'parent.dashboard.pending_fees': 'Pending Fees',
  'parent.dashboard.view_details': 'View Details',
  'parent.dashboard.recent_activities': 'Recent Activities',
  'parent.dashboard.no_recent_activities': 'No recent activities',
  'parent.dashboard.pending_leave_approvals': 'Pending Leave Approvals',
  'parent.dashboard.no_pending_requests': 'No pending requests',
  'parent.dashboard.upcoming_events': 'Upcoming Events',
  'parent.dashboard.no_upcoming_events': 'No upcoming events',
  'parent.dashboard.children_performance_comparison': 'Children Performance Comparison',

  // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.students': 'Students',
  'nav.teachers': 'Teachers',
  'nav.classes': 'Classes',
  'nav.subjects': 'Subjects',
  'nav.exams': 'Exams',
  'nav.fees': 'Fees',
  'nav.timetable': 'Timetable',
  'nav.attendance': 'Attendance',
  'nav.notifications': 'Notifications',
  'nav.settings': 'Settings',
  'nav.my_children': 'My Children',
  'nav.performance': 'Performance',
  'nav.fee_payments': 'Fee Payments',
  'nav.assignments': 'Assignments',
  'nav.quizzes_tests': 'Quizzes & Tests',
  'nav.exams_results': 'Exams & Results',
  'nav.my_attendance': 'My Attendance',
  'nav.fee_payment': 'Fee Payment',
  'nav.my_classes': 'My Classes',
  'nav.my_timetable': 'My Timetable',
  'nav.study_materials': 'Study Materials',
  'nav.quiz_test': 'Quiz & Test',
  'nav.grading': 'Grading',
  'nav.teacher_students': 'Students',
  'nav.finance_tools': 'Finance Tools',
  'nav.notification_tools': 'Notification Tools',
  'nav.admin_reports': 'Admin Reports',

  'parent.performance.title': 'Academic Performance',
  'parent.performance.subtitle': "Track your children's academic progress",
  'parent.performance.select_child': 'Select Child',
  'parent.performance.overall_average': 'Overall Average',
  'parent.performance.class_rank': 'Class Rank',
  'parent.performance.progress': 'Progress',
  'parent.performance.no_data': 'No performance data available',
  'parent.performance.subject_wise': 'Subject-wise Performance',
  'parent.performance.assignments': 'Assignments',
  'parent.performance.exams': 'Exam Results',
  'parent.performance.quizzes': 'Quizzes & Tests',
  'parent.performance.no_assignments': 'No assignments found',
  'parent.performance.no_quizzes': 'No quizzes/tests found',

  'table.title': 'Title',
  'table.subject': 'Subject',
  'table.type': 'Type',
  'table.status': 'Status',
  'table.marks': 'Marks',
  'table.percent': '%',
  'table.result': 'Result',
  'table.student': 'Student',
  'table.class': 'Class',
  'table.submitted': 'Submitted',

  'result.passed': 'Passed',
  'result.failed': 'Failed',

  'student.quizzes.results': 'Results',
  'student.quizzes.attempt': 'Attempt',
  'student.quizzes.score': 'Score',
  'student.quizzes.status': 'Status',
  'student.quizzes.submitted': 'Submitted',
  'student.quizzes.title': 'Quizzes & Tests',
  'student.quizzes.subtitle': 'Start and submit your online quizzes and tests',
  'student.quizzes.type': 'Type',
  'student.quizzes.due': 'Due',
  'student.quizzes.attempts': 'Attempts',
  'student.quizzes.action': 'Action',
  'student.quizzes.start': 'Start',
  'student.quizzes.reattempt': 'Re-attempt',
  'student.quizzes.view_results': 'View Results',
  'student.quizzes.time_remaining': 'Time Remaining',
  'student.quizzes.cancel': 'Cancel',
  'student.quizzes.submit': 'Submit',
  'student.quizzes.no_attempts': 'No attempts found.',
  'student.quizzes.expired': 'This attempt appears to have already expired. Please try starting the quiz again.',
  'student.quizzes.mcq': 'MCQ',
  'student.quizzes.scq': 'SCQ',
};

const hi: Dict = {
  'common.theme': 'थीम',
  'common.english': 'English',
  'common.hindi': 'हिंदी',
  'common.urdu': 'اردو',
  'common.close': 'बंद करें',
  'common.print_certificate': 'प्रमाणपत्र प्रिंट करें',
  'common.loading': 'लोड हो रहा है...',
  'common.cancel': 'रद्द करें',
  'common.submit': 'जमा करें',
  'common.view': 'देखें',
  'common.view_all': 'सभी देखें',
  'common.apply_leave': 'छुट्टी के लिए आवेदन करें',
  'common.details': 'विवरण देखें',

  // Table headers (generic)
  'table.assignment': 'असाइनमेंट',
  'table.due_date': 'अंतिम तिथि',
  'table.action': 'क्रिया',
  'table.due': 'देय',
  'table.attempts': 'प्रयास',

  // Status
  'status.present': 'उपस्थित',
  'status.absent': 'अनुपस्थित',
  'status.late': 'देर',
  'status.excused': 'माफ',
  'status.half_day': 'आधा दिन',

  // Timetable
  'timetable.break': 'विराम',
  'timetable.lunch_break': 'दोपहर का भोजन',

  // Student Dashboard
  'student.dashboard.title': 'छात्र डैशबोर्ड',
  'student.dashboard.welcome': 'वापसी पर स्वागत है, {name}! अपनी पढ़ाई पर ध्यान रखें।',
  'student.dashboard.attendance_rate': 'उपस्थिति दर',
  'student.dashboard.average_grade': 'औसत ग्रेड',
  'student.dashboard.pending': 'लंबित',
  'student.dashboard.exams': 'परीक्षाएं',
  'student.dashboard.done': 'पूरा',
  'student.dashboard.todays_classes': 'आज की कक्षाएं',
  'student.dashboard.pending_assignments': 'लंबित असाइनमेंट',
  'student.dashboard.recent_grades': 'हालिया ग्रेड',
  'student.dashboard.apply_leave': 'छुट्टी के लिए आवेदन करें',
  'student.dashboard.leave_type': 'छुट्टी का प्रकार',
  'student.dashboard.sick_leave': 'बीमारी छुट्टी',
  'student.dashboard.personal': 'व्यक्तिगत',
  'student.dashboard.family_emergency': 'पारिवारिक आपातकाल',
  'student.dashboard.other': 'अन्य',
  'student.dashboard.start_date': 'प्रारंभ तिथि',
  'student.dashboard.end_date': 'समाप्ति तिथि',
  'student.dashboard.reason': 'कारण',
  'student.dashboard.leave_info': 'आपका आवेदन अभिभावक और फिर एडमिन को भेजा जाएगा।',
  'student.dashboard.submit_application': 'आवेदन जमा करें',

  // Teacher Dashboard
  'teacher.dashboard.title': 'शिक्षक डैशबोर्ड',
  'teacher.dashboard.welcome': 'स्वागत है, {name}! आज की कक्षाओं के लिए तैयार?',
  'teacher.dashboard.leave_balances': 'छुट्टी शेष',
  'teacher.dashboard.apply_leave': 'छुट्टी के लिए आवेदन',
  'teacher.dashboard.privilege': 'विशेषाधिकार',
  'teacher.dashboard.sick': 'बीमारी',
  'teacher.dashboard.my_classes': 'मेरी कक्षाएं',
  'teacher.dashboard.students': 'छात्र',
  'teacher.dashboard.assignments': 'असाइनमेंट',
  'teacher.dashboard.to_grade': 'जांच हेतु',
  'teacher.dashboard.today': 'आज',
  'teacher.dashboard.attendance': 'उपस्थिति',
  'teacher.dashboard.todays_schedule': 'आज का कार्यक्रम',
  'teacher.dashboard.classes_count': 'कक्षाएं',
  'teacher.dashboard.quick_actions': 'त्वरित क्रियाएँ',
  'teacher.dashboard.mark_attendance': 'उपस्थिति दर्ज करें',
  'teacher.dashboard.create_assignment': 'असाइनमेंट बनाएं',
  'teacher.dashboard.grade_submissions': 'मूल्यांकन करें',
  'teacher.dashboard.send_announcement': 'घोषणा भेजें',
  'teacher.dashboard.recent_submissions': 'हालिया सबमिशन',
  'teacher.dashboard.start_class': 'कक्षा शुरू करें',

  // Parent Dashboard
  'parent.dashboard.title': 'अभिभावक डैशबोर्ड',
  'parent.dashboard.welcome': 'स्वागत है, {name}! बच्चों की प्रगति देखें।',
  'parent.dashboard.attendance': 'उपस्थिति',
  'parent.dashboard.average_grade': 'औसत ग्रेड',
  'parent.dashboard.upcoming_exams': 'आगामी परीक्षाएं',
  'parent.dashboard.pending_fees': 'बकाया शुल्क',
  'parent.dashboard.view_details': 'विवरण देखें',
  'parent.dashboard.recent_activities': 'हालिया गतिविधियां',
  'parent.dashboard.no_recent_activities': 'कोई हालिया गतिविधि नहीं',
  'parent.dashboard.pending_leave_approvals': 'लंबित छुट्टी अनुमोदन',
  'parent.dashboard.no_pending_requests': 'कोई लंबित अनुरोध नहीं',
  'parent.dashboard.upcoming_events': 'आगामी कार्यक्रम',
  'parent.dashboard.no_upcoming_events': 'कोई आगामी कार्यक्रम नहीं',
  'parent.dashboard.children_performance_comparison': 'बच्चों का प्रदर्शन तुलना',

  // Navigation
  'nav.dashboard': 'डैशबोर्ड',
  'nav.students': 'छात्र',
  'nav.teachers': 'शिक्षक',
  'nav.classes': 'कक्षाएं',
  'nav.subjects': 'विषय',
  'nav.exams': 'परीक्षाएं',
  'nav.fees': 'शुल्क',
  'nav.timetable': 'समय सारिणी',
  'nav.attendance': 'उपस्थिति',
  'nav.notifications': 'सूचनाएँ',
  'nav.settings': 'सेटिंग्स',
  'nav.my_children': 'मेरे बच्चे',
  'nav.performance': 'प्रदर्शन',
  'nav.fee_payments': 'शुल्क भुगतान',
  'nav.assignments': 'असाइनमेंट',
  'nav.quizzes_tests': 'क्विज़ और टेस्ट',
  'nav.exams_results': 'परीक्षा और परिणाम',
  'nav.my_attendance': 'मेरी उपस्थिति',
  'nav.fee_payment': 'शुल्क भुगतान',
  'nav.my_classes': 'मेरी कक्षाएं',
  'nav.my_timetable': 'मेरा समय सारिणी',
  'nav.study_materials': 'अध्ययन सामग्री',
  'nav.quiz_test': 'क्विज़ और टेस्ट',
  'nav.grading': 'ग्रेडिंग',
  'nav.teacher_students': 'छात्र',
  'nav.finance_tools': 'वित्त उपकरण',
  'nav.notification_tools': 'सूचना उपकरण',
  'nav.admin_reports': 'एडमिन रिपोर्ट्स',

  'parent.performance.title': 'शैक्षणिक प्रदर्शन',
  'parent.performance.subtitle': 'अपने बच्चों की प्रगति देखें',
  'parent.performance.select_child': 'बच्चा चुनें',
  'parent.performance.overall_average': 'कुल औसत',
  'parent.performance.class_rank': 'कक्षा रैंक',
  'parent.performance.progress': 'प्रगति',
  'parent.performance.no_data': 'कोई डेटा उपलब्ध नहीं',
  'parent.performance.subject_wise': 'विषय-वार प्रदर्शन',
  'parent.performance.assignments': 'असाइनमेंट',
  'parent.performance.exams': 'परीक्षा परिणाम',
  'parent.performance.quizzes': 'क्विज़ और टेस्ट',
  'parent.performance.no_assignments': 'कोई असाइनमेंट नहीं मिला',
  'parent.performance.no_quizzes': 'कोई क्विज़/टेस्ट नहीं मिला',

  'table.title': 'शीर्षक',
  'table.subject': 'विषय',
  'table.type': 'प्रकार',
  'table.status': 'स्थिति',
  'table.marks': 'अंक',
  'table.percent': '%',
  'table.result': 'परिणाम',
  'table.student': 'छात्र',
  'table.class': 'कक्षा',
  'table.submitted': 'जमा किया',

  'result.passed': 'उत्तीर्ण',
  'result.failed': 'अनुत्तीर्ण',

  'student.quizzes.results': 'परिणाम',
  'student.quizzes.attempt': 'प्रयास',
  'student.quizzes.score': 'स्कोर',
  'student.quizzes.status': 'स्थिति',
  'student.quizzes.submitted': 'जमा किया',
  'student.quizzes.title': 'क्विज़ और टेस्ट',
  'student.quizzes.subtitle': 'अपने ऑनलाइन क्विज़ और टेस्ट शुरू करें और जमा करें',
  'student.quizzes.type': 'प्रकार',
  'student.quizzes.due': 'देय',
  'student.quizzes.attempts': 'प्रयास',
  'student.quizzes.action': 'क्रिया',
  'student.quizzes.start': 'शुरू करें',
  'student.quizzes.reattempt': 'पुनः प्रयास',
  'student.quizzes.view_results': 'परिणाम देखें',
  'student.quizzes.time_remaining': 'शेष समय',
  'student.quizzes.cancel': 'रद्द करें',
  'student.quizzes.submit': 'जमा करें',
  'student.quizzes.no_attempts': 'कोई प्रयास नहीं मिला।',
  'student.quizzes.expired': 'यह प्रयास पहले ही समाप्त हो चुका है। कृपया दोबारा शुरू करें।',
  'student.quizzes.mcq': 'बहुविकल्पी',
  'student.quizzes.scq': 'एकल विकल्प',
};

const ur: Dict = {
  'common.theme': 'تھیم',
  'common.english': 'English',
  'common.hindi': 'हिंदी',
  'common.urdu': 'اردو',
  'common.close': 'بند کریں',
  'common.print_certificate': 'سرٹیفکیٹ پرنٹ کریں',
  'common.loading': 'لوڈ ہو رہا ہے...',
  'common.cancel': 'منسوخ کریں',
  'common.submit': 'جمع کریں',
  'common.view': 'دیکھیں',
  'common.view_all': 'سب دیکھیں',
  'common.apply_leave': 'چھٹی کی درخواست',
  'common.details': 'تفصیلات دیکھیں',

  // Table headers (generic)
  'table.assignment': 'اسائنمنٹ',
  'table.due_date': 'آخری تاریخ',
  'table.action': 'عمل',
  'table.due': 'واجب الادا',
  'table.attempts': 'کوششیں',

  // Status
  'status.present': 'حاضر',
  'status.absent': 'غیر حاضر',
  'status.late': 'تاخیر',
  'status.excused': 'معاف',
  'status.half_day': 'نصف دن',

  // Timetable
  'timetable.break': 'وقفہ',
  'timetable.lunch_break': 'لنچ وقفہ',

  // Student Dashboard
  'student.dashboard.title': 'طلبہ ڈیش بورڈ',
  'student.dashboard.welcome': 'خوش آمدید، {name}! اپنی پڑھائی پر توجہ دیں۔',
  'student.dashboard.attendance_rate': 'حاضری کی شرح',
  'student.dashboard.average_grade': 'اوسط گریڈ',
  'student.dashboard.pending': 'زیر التواء',
  'student.dashboard.exams': 'امتحانات',
  'student.dashboard.done': 'مکمل',
  'student.dashboard.todays_classes': 'آج کی کلاسیں',
  'student.dashboard.pending_assignments': 'زیر التواء اسائنمنٹس',
  'student.dashboard.recent_grades': 'حالیہ گریڈز',
  'student.dashboard.apply_leave': 'چھٹی کی درخواست',
  'student.dashboard.leave_type': 'چھٹی کی قسم',
  'student.dashboard.sick_leave': 'بیماری کی چھٹی',
  'student.dashboard.personal': 'ذاتی',
  'student.dashboard.family_emergency': 'خاندانی ایمرجنسی',
  'student.dashboard.other': 'دیگر',
  'student.dashboard.start_date': 'شروع ہونے کی تاریخ',
  'student.dashboard.end_date': 'اختتامی تاریخ',
  'student.dashboard.reason': 'وجہ',
  'student.dashboard.leave_info': 'آپ کی درخواست والدین اور پھر منتظم کو بھیجی جائے گی۔',
  'student.dashboard.submit_application': 'درخواست جمع کریں',

  // Teacher Dashboard
  'teacher.dashboard.title': 'اساتذہ ڈیش بورڈ',
  'teacher.dashboard.welcome': 'خوش آمدید، {name}! آج کی کلاسوں کے لیے تیار؟',
  'teacher.dashboard.leave_balances': 'چھٹی بیلنس',
  'teacher.dashboard.apply_leave': 'چھٹی کے لیے درخواست',
  'teacher.dashboard.privilege': 'خصوصی',
  'teacher.dashboard.sick': 'بیماری',
  'teacher.dashboard.my_classes': 'میری کلاسز',
  'teacher.dashboard.students': 'طلباء',
  'teacher.dashboard.assignments': 'اسائنمنٹس',
  'teacher.dashboard.to_grade': 'جائزہ',
  'teacher.dashboard.today': 'آج',
  'teacher.dashboard.attendance': 'حاضری',
  'teacher.dashboard.todays_schedule': 'آج کا شیڈول',
  'teacher.dashboard.classes_count': 'کلاسز',
  'teacher.dashboard.quick_actions': 'فوری اعمال',
  'teacher.dashboard.mark_attendance': 'حاضری درج کریں',
  'teacher.dashboard.create_assignment': 'اسائنمنٹ بنائیں',
  'teacher.dashboard.grade_submissions': 'گریڈ کریں',
  'teacher.dashboard.send_announcement': 'اعلان بھیجیں',
  'teacher.dashboard.recent_submissions': 'حالیہ جمع کرائیں',
  'teacher.dashboard.start_class': 'کلاس شروع کریں',

  // Parent Dashboard
  'parent.dashboard.title': 'والدین ڈیش بورڈ',
  'parent.dashboard.welcome': 'خوش آمدید، {name}! بچوں کی کارکردگی دیکھیں۔',
  'parent.dashboard.attendance': 'حاضری',
  'parent.dashboard.average_grade': 'اوسط گریڈ',
  'parent.dashboard.upcoming_exams': 'آئندہ امتحانات',
  'parent.dashboard.pending_fees': 'بقیہ فیس',
  'parent.dashboard.view_details': 'تفصیل دیکھیں',
  'parent.dashboard.recent_activities': 'تازہ سرگرمیاں',
  'parent.dashboard.no_recent_activities': 'کوئی تازہ سرگرمی نہیں',
  'parent.dashboard.pending_leave_approvals': 'زیر التواء چھٹی منظوری',
  'parent.dashboard.no_pending_requests': 'کوئی زیر التواء درخواست نہیں',
  'parent.dashboard.upcoming_events': 'آئندہ تقریبات',
  'parent.dashboard.no_upcoming_events': 'کوئی آئندہ تقریب نہیں',
  'parent.dashboard.children_performance_comparison': 'بچوں کی کارکردگی موازنہ',

  // Navigation
  'nav.dashboard': 'ڈیش بورڈ',
  'nav.students': 'طلباء',
  'nav.teachers': 'اساتذہ',
  'nav.classes': 'کLASسز',
  'nav.subjects': 'مضامین',
  'nav.exams': 'امتحانات',
  'nav.fees': 'فیس',
  'nav.timetable': 'ٹائم ٹیبل',
  'nav.attendance': 'حاضری',
  'nav.notifications': 'اطلاعات',
  'nav.settings': 'سیٹنگز',
  'nav.my_children': 'میرے بچے',
  'nav.performance': 'کارکردگی',
  'nav.fee_payments': 'فیس ادائیگی',
  'nav.assignments': 'اسائنمنٹس',
  'nav.quizzes_tests': 'کوئز و ٹیسٹ',
  'nav.exams_results': 'امتحانات و نتائج',
  'nav.my_attendance': 'میری حاضری',
  'nav.fee_payment': 'فیس ادائیگی',
  'nav.my_classes': 'میری کلاسز',
  'nav.my_timetable': 'میرا ٹائم ٹیبل',
  'nav.study_materials': 'مطالعہ مواد',
  'nav.quiz_test': 'کوئز و ٹیسٹ',
  'nav.grading': 'گریڈنگ',
  'nav.teacher_students': 'طلباء',
  'nav.finance_tools': 'مالیاتی ٹولز',
  'nav.notification_tools': 'اطلاعی ٹولز',
  'nav.admin_reports': 'ایڈمن رپورٹس',

  'parent.performance.title': 'تعلیمی کارکردگی',
  'parent.performance.subtitle': 'اپنے بچوں کی کارکردگی دیکھیں',
  'parent.performance.select_child': 'بچے کا انتخاب کریں',
  'parent.performance.overall_average': 'مجموعی اوسط',
  'parent.performance.class_rank': 'کلاس درجہ',
  'parent.performance.progress': 'پیش رفت',
  'parent.performance.no_data': 'کوئی ڈیٹا دستیاب نہیں',
  'parent.performance.subject_wise': 'موضوع کے لحاظ سے کارکردگی',
  'parent.performance.assignments': 'اسائنمنٹس',
  'parent.performance.exams': 'امتحانی نتائج',
  'parent.performance.quizzes': 'کوئز و ٹیسٹ',
  'parent.performance.no_assignments': 'کوئی اسائنمنٹ نہیں ملا',
  'parent.performance.no_quizzes': 'کوئی کوئز/ٹیسٹ نہیں ملا',

  'table.title': 'عنوان',
  'table.subject': 'مضمون',
  'table.type': 'قسم',
  'table.status': 'حالت',
  'table.marks': 'نمبر',
  'table.percent': '%',
  'table.result': 'نتیجہ',
  'table.student': 'طالب علم',
  'table.class': 'کلاس',
  'table.submitted': 'جمع کیا گیا',

  'result.passed': 'کامیاب',
  'result.failed': 'ناکام',

  'student.quizzes.results': 'نتائج',
  'student.quizzes.attempt': 'کوشش',
  'student.quizzes.score': 'اسکور',
  'student.quizzes.status': 'حالت',
  'student.quizzes.submitted': 'جمع کیا',
  'student.quizzes.title': 'کوئز و ٹیسٹ',
  'student.quizzes.subtitle': 'اپنے آن لائن کوئز اور ٹیسٹ شروع کریں اور جمع کریں',
  'student.quizzes.type': 'قسم',
  'student.quizzes.due': 'واجب الادا',
  'student.quizzes.attempts': 'کوششیں',
  'student.quizzes.action': 'عمل',
  'student.quizzes.start': 'شروع کریں',
  'student.quizzes.reattempt': 'دوبارہ کوشش',
  'student.quizzes.view_results': 'نتائج دیکھیں',
  'student.quizzes.time_remaining': 'باقی وقت',
  'student.quizzes.cancel': 'منسوخ کریں',
  'student.quizzes.submit': 'جمع کریں',
  'student.quizzes.no_attempts': 'کوئی کوشش نہیں ملی۔',
  'student.quizzes.expired': 'یہ کوشش پہلے ہی ختم ہو چکی ہے۔ براہ کرم دوبارہ شروع کریں۔',
  'student.quizzes.mcq': 'MCQ',
  'student.quizzes.scq': 'SCQ',
};

const dicts: Record<Lang, Dict> = { en, hi, ur };

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  dir: 'ltr' | 'rtl';
  t: (key: string) => string;
};

const LangContext = createContext<Ctx | undefined>(undefined);

export const LangProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = (typeof window !== 'undefined' ? localStorage.getItem('lang') : null) as Lang | null;
    return saved || 'en';
  });

  useEffect(() => {
    try { localStorage.setItem('lang', lang); } catch {}
    try {
      const el = document.documentElement;
      el.setAttribute('lang', lang);
      el.setAttribute('dir', lang === 'ur' ? 'rtl' : 'ltr');
    } catch {}
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);
  const dir: 'ltr' | 'rtl' = lang === 'ur' ? 'rtl' : 'ltr';

  const t = useMemo(() => {
    return (key: string) => {
      const d = dicts[lang] || en;
      return d[key] ?? en[key] ?? key;
    };
  }, [lang]);

  const value: Ctx = { lang, setLang, dir, t };
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
