import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Dict = Record<string, string>;

type Lang = 'en' | 'hi' | 'ur';

const en: Dict = {
  'common.theme': 'Theme',
  'common.english': 'English',
  'common.hindi': 'हिंदी',
  'common.urdu': 'اردو',
  'common.close': 'Close',
  'common.print_certificate': 'Print Certificate',
  'common.loading': 'Loading...',
  'common.cancel': 'Cancel',
  'common.submit': 'Submit',
  'common.view': 'View',
  'common.view_all': 'View All',
  'common.apply_leave': 'Apply for Leave',
  'common.details': 'View Details',
  'common.days': 'days',
  'common.saving': 'Saving...',
  'common.save': 'Save',
  'common.fetch': 'Fetch',
  'common.download_csv': 'Download CSV',
  'common.add': 'Add',
  'common.remove': 'Remove',

  // Table headers (generic)
  'table.assignment': 'Assignment',
  'table.due_date': 'Due Date',
  'table.action': 'Action',
  'table.due': 'Due',
  'table.attempts': 'Attempts',

  // Status
  'status.present': 'Present',
  'status.absent': 'Absent',
  'status.late': 'Late',
  'status.excused': 'Excused',
  'status.half_day': 'Half Day',
  'status.graded': 'Graded',
  'status.submitted': 'Submitted',
  'status.pending': 'Pending',

  // Timetable
  'timetable.break': 'Break',
  'timetable.lunch_break': 'Lunch Break',

  // Student Dashboard
  'student.dashboard.title': 'Student Dashboard',
  'student.dashboard.welcome': 'Welcome back, {name}! Stay on top of your studies.',
  'student.dashboard.attendance_rate': 'Attendance Rate',
  'student.dashboard.average_grade': 'Average Grade',
  'student.dashboard.pending': 'Pending',
  'student.dashboard.exams': 'Exams',
  'student.dashboard.done': 'Done',
  'student.dashboard.todays_classes': "Today's Classes",
  'student.dashboard.pending_assignments': 'Pending Assignments',
  'student.dashboard.recent_grades': 'Recent Grades',
  'student.dashboard.apply_leave': 'Apply for Leave',
  'student.dashboard.leave_type': 'Leave Type',
  'student.dashboard.sick_leave': 'Sick Leave',
  'student.dashboard.personal': 'Personal',
  'student.dashboard.family_emergency': 'Family Emergency',
  'student.dashboard.other': 'Other',
  'student.dashboard.start_date': 'Start Date',
  'student.dashboard.end_date': 'End Date',
  'student.dashboard.reason': 'Reason',
  'student.dashboard.leave_info': 'Your leave application will be sent to your parent for approval, then forwarded to admin.',
  'student.dashboard.submit_application': 'Submit Application',
  'student.dashboard.leave_submitted': 'Leave application submitted successfully!',
  'student.dashboard.reason_placeholder': 'Explain the reason for your leave...',

  // Teacher Dashboard
  'teacher.dashboard.title': 'Teacher Dashboard',
  'teacher.dashboard.welcome': "Welcome, {name}! Ready for today's classes?",
  'teacher.dashboard.leave_balances': 'Leave Balances',
  'teacher.dashboard.apply_leave': 'Apply Leave',
  'teacher.dashboard.privilege': 'Privilege',
  'teacher.dashboard.sick': 'Sick',
  'teacher.dashboard.my_classes': 'My Classes',
  'teacher.dashboard.students': 'Students',
  'teacher.dashboard.assignments': 'Assignments',
  'teacher.dashboard.to_grade': 'To Grade',
  'teacher.dashboard.today': 'Today',
  'teacher.dashboard.attendance': 'Attendance',
  'teacher.dashboard.todays_schedule': "Today's Schedule",
  'teacher.dashboard.classes_count': 'Classes',
  'teacher.dashboard.quick_actions': 'Quick Actions',
  'teacher.dashboard.mark_attendance': 'Mark Attendance',
  'teacher.dashboard.create_assignment': 'Create Assignment',
  'teacher.dashboard.grade_submissions': 'Grade Submissions',
  'teacher.dashboard.send_announcement': 'Send Announcement',
  'teacher.dashboard.recent_submissions': 'Recent Submissions',
  'teacher.dashboard.start_class': 'Start Class',
  'teacher.dashboard.leave_submitted': 'Leave application submitted',
  'teacher.dashboard.select_dates': 'Please select start and end dates',

  'settings.school.holidays.title': 'Holidays',
  'settings.school.holidays.populate_defaults': 'Populate default Indian Holidays',
  'settings.school.leave_policy.title': 'Teacher Leave Policy',
  'settings.school.leave_policy.privilege_per_year': 'Privilege per year',
  'settings.school.leave_policy.sick_per_year': 'Sick per year',
  'settings.school.school_id_label': 'School ID',
  'settings.school.school_id_placeholder': 'Enter unique school ID (e.g., SCH001)',
  'settings.school.school_id_help': 'School ID can only be set once during first-time configuration',
  'settings.school.school_name_label': 'School Name',
  'settings.school.logo_url_label': 'Logo URL',
  'settings.school.principal_name_label': 'Principal Name (for receipts)',
  'settings.school.example.principal_name': 'e.g., Dr. A. B. Principal',
  'settings.school.principal_signature_label': 'Principal Signature',
  'settings.school.principal_signature_placeholder': 'Signature Image URL',
  'settings.school.signature_uploaded': 'Signature uploaded',
  'settings.school.preview': 'Preview:',
  'settings.school.contact.phone_label': 'Phone',
  'settings.school.contact.email_label': 'Email',
  'settings.school.contact.website_label': 'Website',
  'settings.school.address.street_label': 'Address (Street)',
  'settings.school.address.city_label': 'City',
  'settings.school.address.state_label': 'State',
  'settings.school.address.zip_label': 'Zip Code',
  'settings.school.config.academic_year_label': 'Academic Year',
  'settings.school.config.grade_system_label': 'Grade System',
  'settings.school.config.currency_label': 'Currency',
  'settings.school.config.timezone_label': 'Timezone',
  'settings.school.example.academic_year': 'e.g., 2025-2026',
  'settings.school.example.grade_system': 'e.g., Percentage',
  'settings.school.example.currency': 'e.g., INR',
  'settings.school.example.timezone': 'e.g., Asia/Kolkata',
  'settings.school.config.student_id_format_label': 'Default Student ID Format',
  'settings.school.example.student_id_format': 'e.g., STU-{YYYY}-{SEQ}',
  'settings.school.config.employee_id_format_label': 'Default Employee ID Format',
  'settings.school.example.employee_id_format': 'e.g., EMP-{YYYY}-{SEQ}',
  'error.upload_failed': 'Upload failed',

  // Parent Dashboard
  'parent.dashboard.title': 'Parent Dashboard',
  'parent.dashboard.welcome': "Welcome, {name}! Track your children's progress.",
  'parent.dashboard.attendance': 'Attendance',
  'parent.dashboard.average_grade': 'Average Grade',
  'parent.dashboard.upcoming_exams': 'Upcoming Exams',
  'parent.dashboard.pending_fees': 'Pending Fees',
  'parent.dashboard.view_details': 'View Details',
  'parent.dashboard.recent_activities': 'Recent Activities',
  'parent.dashboard.no_recent_activities': 'No recent activities',
  'parent.dashboard.pending_leave_approvals': 'Pending Leave Approvals',
  'parent.dashboard.no_pending_requests': 'No pending requests',
  'parent.dashboard.upcoming_events': 'Upcoming Events',
  'parent.dashboard.no_upcoming_events': 'No upcoming events',
  'parent.dashboard.children_performance_comparison': 'Children Performance Comparison',
  'parent.dashboard.reason_rejection_prompt': 'Reason for rejection?',
  'parent.dashboard.rejected_by_parent': 'Rejected by parent',

  'error.fill_required_fields': 'Please fill all required fields',
  'error.failed_to_submit_leave': 'Failed to submit leave application',
  'error.failed_to_apply_leave': 'Failed to apply for leave',
  'error.failed_to_load_dashboard': 'Failed to load dashboard',
  'error.failed_to_load_quizzes': 'Failed to load quizzes',
  'error.failed_to_start_quiz': 'Failed to start quiz',
  'error.failed_to_load_results': 'Failed to load results',
  'error.failed_to_submit_quiz': 'Failed to submit quiz',
  'error.failed_to_approve_leave': 'Failed to approve leave',
  'error.failed_to_reject_leave': 'Failed to reject leave',
  'error.failed_to_fetch_class_stats': 'Failed to fetch class stats',
  'error.failed_to_fetch_teacher_stats': 'Failed to fetch teacher stats',
  'error.failed_to_fetch_finance_summary': 'Failed to fetch finance summary',
  'error.failed_to_load_children': 'Failed to load children',
  'error.failed_to_load_performance': 'Failed to load performance',

  'time.just_now': 'Just now',
  'time.mins_ago': '{mins} mins ago',
  'time.hours_ago': '{hours} hours ago',
  'time.days_ago': '{days} days ago',

  // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.students': 'Students',
  'nav.teachers': 'Teachers',
  'nav.classes': 'Classes',
  'nav.subjects': 'Subjects',
  'nav.exams': 'Exams',
  'nav.fees': 'Fees',
  'nav.timetable': 'Timetable',
  'nav.attendance': 'Attendance',
  'nav.notifications': 'Notifications',
  'nav.settings': 'Settings',
  'nav.my_children': 'My Children',
  'nav.performance': 'Performance',
  'nav.fee_payments': 'Fee Payments',
  'nav.assignments': 'Assignments',
  'nav.quizzes_tests': 'Quizzes & Tests',
  'nav.exams_results': 'Exams & Results',
  'nav.my_attendance': 'My Attendance',
  'nav.fee_payment': 'Fee Payment',
  'nav.my_classes': 'My Classes',
  'nav.my_timetable': 'My Timetable',
  'nav.study_materials': 'Study Materials',
  'nav.quiz_test': 'Quiz & Test',
  'nav.grading': 'Grading',
  'nav.teacher_students': 'Students',
  'nav.finance_tools': 'Finance Tools',
  'nav.notification_tools': 'Notification Tools',
  'nav.admin_reports': 'Admin Reports',

  'admin.reports.subtitle': 'Download Class, Teacher and Finance summaries (CSV). Excel/PDF coming next.',
  'admin.reports.class_stats': 'Class-wise Statistics',
  'admin.reports.teacher_report': 'Teacher Report',
  'admin.reports.finance_summary': 'Finance Summary',
  'admin.reports.select_class': 'Select Class',
  'admin.reports.select_school': 'Select School',
  'admin.reports.teacher_id_placeholder': 'Teacher ID',

  'parent.performance.rating.excellent': 'Excellent',
  'parent.performance.rating.good': 'Good',
  'parent.performance.rating.needs_attention': 'Needs Attention',

  'parent.performance.title': 'Academic Performance',
  'parent.performance.subtitle': "Track your children's academic progress",
  'parent.performance.select_child': 'Select Child',
  'parent.performance.overall_average': 'Overall Average',
  'parent.performance.class_rank': 'Class Rank',
  'parent.performance.progress': 'Progress',
  'parent.performance.no_data': 'No performance data available',
  'parent.performance.subject_wise': 'Subject-wise Performance',
  'parent.performance.assignments': 'Assignments',
  'parent.performance.exams': 'Exam Results',
  'parent.performance.quizzes': 'Quizzes & Tests',
  'parent.performance.no_assignments': 'No assignments found',
  'parent.performance.no_quizzes': 'No quizzes/tests found',

  'table.title': 'Title',
  'table.subject': 'Subject',
  'table.type': 'Type',
  'table.status': 'Status',
  'table.marks': 'Marks',
  'table.percent': '%',
  'table.result': 'Result',
  'table.student': 'Student',
  'table.class': 'Class',
  'table.submitted': 'Submitted',
  'table.grade': 'Grade',
  'table.date': 'Date',
  'table.quiz': 'Quiz',
  'table.exam': 'Exam',

  'result.passed': 'Passed',
  'result.failed': 'Failed',

  'student.quizzes.results': 'Results',
  'student.quizzes.attempt': 'Attempt',
  'student.quizzes.score': 'Score',
  'student.quizzes.status': 'Status',
  'student.quizzes.submitted': 'Submitted',
  'student.quizzes.title': 'Quizzes & Tests',
  'student.quizzes.subtitle': 'Start and submit your online quizzes and tests',
  'student.quizzes.type': 'Type',
  'student.quizzes.due': 'Due',
  'student.quizzes.attempts': 'Attempts',
  'student.quizzes.action': 'Action',
  'student.quizzes.start': 'Start',
  'student.quizzes.reattempt': 'Re-attempt',
  'student.quizzes.view_results': 'View Results',
  'student.quizzes.time_remaining': 'Time Remaining',
  'student.quizzes.cancel': 'Cancel',
  'student.quizzes.submit': 'Submit',
  'student.quizzes.no_attempts': 'No attempts found.',
  'student.quizzes.expired': 'This attempt appears to have already expired. Please try starting the quiz again.',
  'student.quizzes.mcq': 'MCQ',
  'student.quizzes.scq': 'SCQ',
  'student.quizzes.submitted_label': 'Submitted.',
  'student.quizzes.score_label': 'Score',
  'student.quizzes.option': 'Option {n}',
  'student.quizzes.q_prefix': 'Q',
  'student.quizzes.question_image': 'Question image',
  'student.quizzes.your_best': 'Your Best',
  'student.quizzes.rank_of': 'Rank #{rank} of {participants}',
  'student.quizzes.avg': 'Avg {avg}%',
  'student.quizzes.top': 'Top {top}%',
};

const hi: Dict = {
  'common.theme': 'थीम',
  'common.english': 'English',
  'common.hindi': 'हिंदी',
  'common.urdu': 'اردو',
  'common.close': 'बंद करें',
  'common.print_certificate': 'प्रमाणपत्र प्रिंट करें',
  'common.loading': 'लोड हो रहा है...',
  'common.cancel': 'रद्द करें',
  'common.submit': 'जमा करें',
  'common.view': 'देखें',
  'common.view_all': 'सभी देखें',
  'common.apply_leave': 'छुट्टी के लिए आवेदन करें',
  'common.details': 'विवरण देखें',
  'common.days': 'दिन',
  'common.saving': 'सहेजा जा रहा है...',
  'common.save': 'सहेजें',
  'common.fetch': 'प्राप्त करें',
  'common.download_csv': 'CSV डाउनलोड करें',
  'common.add': 'जोड़ें',
  'common.remove': 'हटाएं',

  // Table headers (generic)
  'table.assignment': 'असाइनमेंट',
  'table.due_date': 'अंतिम तिथि',
  'table.action': 'क्रिया',
  'table.due': 'देय',
  'table.attempts': 'प्रयास',

  // Status
  'status.present': 'उपस्थित',
  'status.absent': 'अनुपस्थित',
  'status.late': 'देर',
  'status.excused': 'माफ',
  'status.half_day': 'आधा दिन',
  'status.graded': 'मूल्यांकित',
  'status.submitted': 'जमा किया',
  'status.pending': 'लंबित',

  // Timetable
  'timetable.break': 'विराम',
  'timetable.lunch_break': 'दोपहर का भोजन',

  // Student Dashboard
  'student.dashboard.title': 'छात्र डैशबोर्ड',
  'student.dashboard.welcome': 'वापसी पर स्वागत है, {name}! अपनी पढ़ाई पर ध्यान रखें।',
  'student.dashboard.attendance_rate': 'उपस्थिति दर',
  'student.dashboard.average_grade': 'औसत ग्रेड',
  'student.dashboard.pending': 'लंबित',
  'student.dashboard.exams': 'परीक्षाएं',
  'student.dashboard.done': 'पूरा',
  'student.dashboard.todays_classes': 'आज की कक्षाएं',
  'student.dashboard.pending_assignments': 'लंबित असाइनमेंट',
  'student.dashboard.recent_grades': 'हालिया ग्रेड',
  'student.dashboard.apply_leave': 'छुट्टी के लिए आवेदन करें',
  'student.dashboard.leave_type': 'छुट्टी का प्रकार',
  'student.dashboard.sick_leave': 'बीमारी छुट्टी',
  'student.dashboard.personal': 'व्यक्तिगत',
  'student.dashboard.family_emergency': 'पारिवारिक आपातकाल',
  'student.dashboard.other': 'अन्य',
  'student.dashboard.start_date': 'प्रारंभ तिथि',
  'student.dashboard.end_date': 'समाप्ति तिथि',
  'student.dashboard.reason': 'कारण',
  'student.dashboard.leave_info': 'आपका आवेदन अभिभावक और फिर एडमिन को भेजा जाएगा।',
  'student.dashboard.submit_application': 'आवेदन जमा करें',
  'student.dashboard.leave_submitted': 'छुट्टी आवेदन सफलतापूर्वक जमा किया गया!',
  'student.dashboard.reason_placeholder': 'अपनी छुट्टी का कारण बताएं...',

  // Teacher Dashboard
  'teacher.dashboard.title': 'शिक्षक डैशबोर्ड',
  'teacher.dashboard.welcome': 'स्वागत है, {name}! आज की कक्षाओं के लिए तैयार?',
  'teacher.dashboard.leave_balances': 'छुट्टी शेष',
  'teacher.dashboard.apply_leave': 'छुट्टी के लिए आवेदन',
  'teacher.dashboard.privilege': 'विशेषाधिकार',
  'teacher.dashboard.sick': 'बीमारी',
  'teacher.dashboard.my_classes': 'मेरी कक्षाएं',
  'teacher.dashboard.students': 'छात्र',
  'teacher.dashboard.assignments': 'असाइनमेंट',
  'teacher.dashboard.to_grade': 'जांच हेतु',
  'teacher.dashboard.today': 'आज',
  'teacher.dashboard.attendance': 'उपस्थिति',
  'teacher.dashboard.todays_schedule': 'आज का कार्यक्रम',
  'teacher.dashboard.classes_count': 'कक्षाएं',
  'teacher.dashboard.quick_actions': 'त्वरित क्रियाएँ',
  'teacher.dashboard.mark_attendance': 'उपस्थिति दर्ज करें',
  'teacher.dashboard.create_assignment': 'असाइनमेंट बनाएं',
  'teacher.dashboard.grade_submissions': 'मूल्यांकन करें',
  'teacher.dashboard.send_announcement': 'घोषणा भेजें',
  'teacher.dashboard.recent_submissions': 'हालिया सबमिशन',
  'teacher.dashboard.start_class': 'कक्षा शुरू करें',
  'teacher.dashboard.leave_submitted': 'छुट्टी आवेदन जमा किया गया',
  'teacher.dashboard.select_dates': 'कृपया प्रारंभ और समाप्ति तिथियाँ चुनें',

  'settings.school.holidays.title': 'अवकाश',
  'settings.school.holidays.populate_defaults': 'डिफ़ॉल्ट भारतीय अवकाश जोड़ें',
  'settings.school.leave_policy.title': 'शिक्षक अवकाश नीति',
  'settings.school.leave_policy.privilege_per_year': 'प्रति वर्ष विशेषाधिकार',
  'settings.school.leave_policy.sick_per_year': 'प्रति वर्ष बीमारी',
  'settings.school.school_id_label': 'स्कूल आईडी',
  'settings.school.school_id_placeholder': 'अद्वितीय स्कूल आईडी दर्ज करें (जैसे, SCH001)',
  'settings.school.school_id_help': 'स्कूल आईडी केवल पहली बार कॉन्फ़िगरेशन के दौरान ही सेट की जा सकती है',
  'settings.school.school_name_label': 'स्कूल का नाम',
  'settings.school.logo_url_label': 'लोगो URL',
  'settings.school.principal_name_label': 'प्राचार्य का नाम (रसीदों के लिए)',
  'settings.school.example.principal_name': 'उदा., डॉ. ए. बी. प्रिंसिपल',
  'settings.school.principal_signature_label': 'प्राचार्य हस्ताक्षर',
  'settings.school.principal_signature_placeholder': 'हस्ताक्षर छवि URL',
  'settings.school.signature_uploaded': 'हस्ताक्षर अपलोड हो गया',
  'settings.school.preview': 'पूर्वावलोकन:',
  'settings.school.contact.phone_label': 'फोन',
  'settings.school.contact.email_label': 'ईमेल',
  'settings.school.contact.website_label': 'वेबसाइट',
  'settings.school.address.street_label': 'पता (सड़क)',
  'settings.school.address.city_label': 'शहर',
  'settings.school.address.state_label': 'राज्य',
  'settings.school.address.zip_label': 'पिन कोड',
  'settings.school.config.academic_year_label': 'शैक्षणिक वर्ष',
  'settings.school.config.grade_system_label': 'ग्रेड प्रणाली',
  'settings.school.config.currency_label': 'मुद्रा',
  'settings.school.config.timezone_label': 'समयक्षेत्र',
  'settings.school.example.academic_year': 'उदा., 2025-2026',
  'settings.school.example.grade_system': 'उदा., प्रतिशत',
  'settings.school.example.currency': 'उदा., INR',
  'settings.school.example.timezone': 'उदा., Asia/Kolkata',
  'settings.school.config.student_id_format_label': 'डिफ़ॉल्ट छात्र आईडी प्रारूप',
  'settings.school.example.student_id_format': 'उदा., STU-{YYYY}-{SEQ}',
  'settings.school.config.employee_id_format_label': 'डिफ़ॉल्ट कर्मचारी आईडी प्रारूप',
  'settings.school.example.employee_id_format': 'उदा., EMP-{YYYY}-{SEQ}',
  'error.upload_failed': 'अपलोड विफल',

  // Parent Dashboard
  'parent.dashboard.title': 'अभिभावक डैशबोर्ड',
  'parent.dashboard.welcome': 'स्वागत है, {name}! बच्चों की प्रगति देखें।',
  'parent.dashboard.attendance': 'उपस्थिति',
  'parent.dashboard.average_grade': 'औसत ग्रेड',
  'parent.dashboard.upcoming_exams': 'आगामी परीक्षाएं',
  'parent.dashboard.pending_fees': 'बकाया शुल्क',
  'parent.dashboard.view_details': 'विवरण देखें',
  'parent.dashboard.recent_activities': 'हालिया गतिविधियां',
  'parent.dashboard.no_recent_activities': 'कोई हालिया गतिविधि नहीं',
  'parent.dashboard.pending_leave_approvals': 'लंबित छुट्टी अनुमोदन',
  'parent.dashboard.no_pending_requests': 'कोई लंबित अनुरोध नहीं',
  'parent.dashboard.upcoming_events': 'आगामी कार्यक्रम',
  'parent.dashboard.no_upcoming_events': 'कोई आगामी कार्यक्रम नहीं',
  'parent.dashboard.children_performance_comparison': 'बच्चों का प्रदर्शन तुलना',
  'parent.dashboard.reason_rejection_prompt': 'अस्वीकृति का कारण?',
  'parent.dashboard.rejected_by_parent': 'अभिभावक द्वारा अस्वीकृत',

  'error.fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
  'error.failed_to_submit_leave': 'छुट्टी आवेदन जमा करने में विफल',
  'error.failed_to_apply_leave': 'छुट्टी के लिए आवेदन करने में विफल',
  'error.failed_to_load_dashboard': 'डैशबोर्ड लोड करने में विफल',
  'error.failed_to_load_quizzes': 'क्विज़ लोड करने में विफल',
  'error.failed_to_start_quiz': 'क्विज़ शुरू करने में विफल',
  'error.failed_to_load_results': 'परिणाम लोड करने में विफल',
  'error.failed_to_submit_quiz': 'क्विज़ जमा करने में विफल',
  'error.failed_to_approve_leave': 'छुट्टी स्वीकृत करने में विफल',
  'error.failed_to_reject_leave': 'छुट्टी अस्वीकार करने में विफल',
  'error.failed_to_fetch_class_stats': 'कक्षा आँकड़े प्राप्त करने में विफल',
  'error.failed_to_fetch_teacher_stats': 'शिक्षक आँकड़े प्राप्त करने में विफल',
  'error.failed_to_fetch_finance_summary': 'वित्त सारांश प्राप्त करने में विफल',
  'error.failed_to_load_children': 'बच्चों को लोड करने में विफल',
  'error.failed_to_load_performance': 'प्रदर्शन लोड करने में विफल',

  'time.just_now': 'अभी',
  'time.mins_ago': '{mins} मिनट पहले',
  'time.hours_ago': '{hours} घंटे पहले',
  'time.days_ago': '{days} दिन पहले',

  // Navigation
  'nav.dashboard': 'डैशबोर्ड',
  'nav.students': 'छात्र',
  'nav.teachers': 'शिक्षक',
  'nav.classes': 'कक्षाएं',
  'nav.subjects': 'विषय',
  'nav.exams': 'परीक्षाएं',
  'nav.fees': 'शुल्क',
  'nav.timetable': 'समय सारिणी',
  'nav.attendance': 'उपस्थिति',
  'nav.notifications': 'सूचनाएँ',
  'nav.settings': 'सेटिंग्स',
  'nav.my_children': 'मेरे बच्चे',
  'nav.performance': 'प्रदर्शन',
  'nav.fee_payments': 'शुल्क भुगतान',
  'nav.assignments': 'असाइनमेंट',
  'nav.quizzes_tests': 'क्विज़ और टेस्ट',
  'nav.exams_results': 'परीक्षा और परिणाम',
  'nav.my_attendance': 'मेरी उपस्थिति',
  'nav.fee_payment': 'शुल्क भुगतान',
  'nav.my_classes': 'मेरी कक्षाएं',
  'nav.my_timetable': 'मेरा समय सारिणी',
  'nav.study_materials': 'अध्ययन सामग्री',
  'nav.quiz_test': 'क्विज़ और टेस्ट',
  'nav.grading': 'ग्रेडिंग',
  'nav.teacher_students': 'छात्र',
  'nav.finance_tools': 'वित्त उपकरण',
  'nav.notification_tools': 'सूचना उपकरण',
  'nav.admin_reports': 'एडमिन रिपोर्ट्स',

  'admin.reports.subtitle': 'कक्षा, शिक्षक और वित्त सारांश (CSV) डाउनलोड करें। एक्सेल/पीडीएफ जल्द ही।',
  'admin.reports.class_stats': 'कक्षा-वार सांख्यिकी',
  'admin.reports.teacher_report': 'शिक्षक रिपोर्ट',
  'admin.reports.finance_summary': 'वित्त सारांश',
  'admin.reports.select_class': 'कक्षा चुनें',
  'admin.reports.select_school': 'स्कूल चुनें',
  'admin.reports.teacher_id_placeholder': 'शिक्षक ID',
  'parent.performance.rating.excellent': 'उत्कृष्ट',
  'parent.performance.rating.good': 'अच्छा',
  'parent.performance.rating.needs_attention': 'ध्यान आवश्यक',

  'parent.performance.title': 'शैक्षणिक प्रदर्शन',
  'parent.performance.subtitle': 'अपने बच्चों की प्रगति देखें',
  'parent.performance.select_child': 'बच्चा चुनें',
  'parent.performance.overall_average': 'कुल औसत',
  'parent.performance.class_rank': 'कक्षा रैंक',
  'parent.performance.progress': 'प्रगति',
  'parent.performance.no_data': 'कोई डेटा उपलब्ध नहीं',
  'parent.performance.subject_wise': 'विषय-वार प्रदर्शन',
  'parent.performance.assignments': 'असाइनमेंट',
  'parent.performance.exams': 'परीक्षा परिणाम',
  'parent.performance.quizzes': 'क्विज़ और टेस्ट',
  'parent.performance.no_assignments': 'कोई असाइनमेंट नहीं मिला',
  'parent.performance.no_quizzes': 'कोई क्विज़/टेस्ट नहीं मिला',

  'table.title': 'शीर्षक',
  'table.subject': 'विषय',
  'table.type': 'प्रकार',
  'table.status': 'स्थिति',
  'table.marks': 'अंक',
  'table.percent': '%',
  'table.result': 'परिणाम',
  'table.student': 'छात्र',
  'table.class': 'कक्षा',
  'table.submitted': 'जमा किया',
  'table.grade': 'ग्रेड',
  'table.date': 'तारीख',
  'table.quiz': 'क्विज़',
  'table.exam': 'परीक्षा',

  'result.passed': 'उत्तीर्ण',
  'result.failed': 'अनुत्तीर्ण',

  'student.quizzes.results': 'परिणाम',
  'student.quizzes.attempt': 'प्रयास',
  'student.quizzes.score': 'स्कोर',
  'student.quizzes.status': 'स्थिति',
  'student.quizzes.submitted': 'जमा किया',
  'student.quizzes.title': 'क्विज़ और टेस्ट',
  'student.quizzes.subtitle': 'अपने ऑनलाइन क्विज़ और टेस्ट शुरू करें और जमा करें',
  'student.quizzes.type': 'प्रकार',
  'student.quizzes.due': 'देय',
  'student.quizzes.attempts': 'प्रयास',
  'student.quizzes.action': 'क्रिया',
  'student.quizzes.start': 'शुरू करें',
  'student.quizzes.reattempt': 'पुनः प्रयास',
  'student.quizzes.view_results': 'परिणाम देखें',
  'student.quizzes.time_remaining': 'शेष समय',
  'student.quizzes.cancel': 'रद्द करें',
  'student.quizzes.submit': 'जमा करें',
  'student.quizzes.no_attempts': 'कोई प्रयास नहीं मिला।',
  'student.quizzes.expired': 'यह प्रयास पहले ही समाप्त हो चुका है। कृपया दोबारा शुरू करें।',
  'student.quizzes.mcq': 'बहुविकल्पी',
  'student.quizzes.scq': 'एकल विकल्प',
  'student.quizzes.submitted_label': 'जमा किया।',
  'student.quizzes.score_label': 'स्कोर',
  'student.quizzes.option': 'विकल्प {n}',
  'student.quizzes.q_prefix': 'प्रश्न ',
  'student.quizzes.question_image': 'प्रश्न छवि',
  'student.quizzes.your_best': 'आपका सर्वश्रेष्ठ',
  'student.quizzes.rank_of': 'रैंक #{rank} में से {participants}',
  'student.quizzes.avg': 'औसत {avg}%',
  'student.quizzes.top': 'शीर्ष {top}%',
};

const ur: Dict = {
  'common.theme': 'تھیم',
  'common.english': 'English',
  'common.hindi': 'हिंदी',
  'common.urdu': 'اردو',
  'common.close': 'بند کریں',
  'common.print_certificate': 'سرٹیفکیٹ پرنٹ کریں',
  'common.loading': 'لوڈ ہو رہا ہے...',
  'common.cancel': 'منسوخ کریں',
  'common.submit': 'جمع کریں',
  'common.view': 'دیکھیں',
  'common.view_all': 'سب دیکھیں',
  'common.apply_leave': 'چھٹی کی درخواست',
  'common.details': 'تفصیلات دیکھیں',
  'common.days': 'دن',
  'common.saving': 'محفوظ کیا جا رہا ہے...',
  'common.save': 'محفوظ کریں',
  'common.fetch': 'حاصل کریں',
  'common.download_csv': 'CSV ڈاؤن لوڈ کریں',
  'common.add': 'شامل کریں',
  'common.remove': 'ہٹائیں',

  // Table headers (generic)
  'table.assignment': 'اسائنمنٹ',
  'table.due_date': 'آخری تاریخ',
  'table.action': 'عمل',
  'table.due': 'واجب الادا',
  'table.attempts': 'کوششیں',

  // Status
  'status.present': 'حاضر',
  'status.absent': 'غیر حاضر',
  'status.late': 'تاخیر',
  'status.excused': 'معاف',
  'status.half_day': 'نصف دن',
  'status.graded': 'گریڈ شدہ',
  'status.submitted': 'جمع کرایا گیا',
  'status.pending': 'زیر التواء',

  // Timetable
  'timetable.break': 'وقفہ',
  'timetable.lunch_break': 'لنچ وقفہ',

  // Student Dashboard
  'student.dashboard.title': 'طلبہ ڈیش بورڈ',
  'student.dashboard.welcome': 'خوش آمدید، {name}! اپنی پڑھائی پر توجہ دیں۔',
  'student.dashboard.attendance_rate': 'حاضری کی شرح',
  'student.dashboard.average_grade': 'اوسط گریڈ',
  'student.dashboard.pending': 'زیر التواء',
  'student.dashboard.exams': 'امتحانات',
  'student.dashboard.done': 'مکمل',
  'student.dashboard.todays_classes': 'آج کی کلاسیں',
  'student.dashboard.pending_assignments': 'زیر التواء اسائنمنٹس',
  'student.dashboard.recent_grades': 'حالیہ گریڈز',
  'student.dashboard.apply_leave': 'چھٹی کی درخواست',
  'student.dashboard.leave_type': 'چھٹی کی قسم',
  'student.dashboard.sick_leave': 'بیماری کی چھٹی',
  'student.dashboard.personal': 'ذاتی',
  'student.dashboard.family_emergency': 'خاندانی ایمرجنسی',
  'student.dashboard.other': 'دیگر',
  'student.dashboard.start_date': 'شروع ہونے کی تاریخ',
  'student.dashboard.end_date': 'اختتامی تاریخ',
  'student.dashboard.reason': 'وجہ',
  'student.dashboard.leave_info': 'آپ کی درخواست والدین اور پھر منتظم کو بھیجی جائے گی۔',
  'student.dashboard.submit_application': 'درخواست جمع کریں',
  'student.dashboard.leave_submitted': 'چھٹی کی درخواست کامیابی سے جمع ہو گئی!',
  'student.dashboard.reason_placeholder': 'اپنی چھٹی کی وجہ بیان کریں...',

  // Teacher Dashboard
  'teacher.dashboard.title': 'اساتذہ ڈیش بورڈ',
  'teacher.dashboard.welcome': 'خوش آمدید، {name}! آج کی کلاسوں کے لیے تیار؟',
  'teacher.dashboard.leave_balances': 'چھٹی بیلنس',
  'teacher.dashboard.apply_leave': 'چھٹی کے لیے درخواست',
  'teacher.dashboard.privilege': 'خصوصی',
  'teacher.dashboard.sick': 'بیماری',
  'teacher.dashboard.my_classes': 'میری کلاسز',
  'teacher.dashboard.students': 'طلباء',
  'teacher.dashboard.assignments': 'اسائنمنٹس',
  'teacher.dashboard.to_grade': 'جائزہ',
  'teacher.dashboard.today': 'آج',
  'teacher.dashboard.attendance': 'حاضری',
  'teacher.dashboard.todays_schedule': 'آج کا شیڈول',
  'teacher.dashboard.classes_count': 'کلاسز',
  'teacher.dashboard.quick_actions': 'فوری اعمال',
  'teacher.dashboard.mark_attendance': 'حاضری درج کریں',
  'teacher.dashboard.create_assignment': 'اسائنمنٹ بنائیں',
  'teacher.dashboard.grade_submissions': 'گریڈ کریں',
  'teacher.dashboard.send_announcement': 'اعلان بھیجیں',
  'teacher.dashboard.recent_submissions': 'حالیہ جمع کرائیں',
  'teacher.dashboard.start_class': 'کلاس شروع کریں',
  'teacher.dashboard.leave_submitted': 'چھٹی کی درخواست جمع ہو گئی',
  'teacher.dashboard.select_dates': 'براہ کرم آغاز اور اختتامی تاریخیں منتخب کریں',

  'settings.school.holidays.title': 'چھٹیاں',
  'settings.school.holidays.populate_defaults': 'ڈिफالٹ بھارتی چھٹیاں شامل کریں',
  'settings.school.leave_policy.title': 'اساتذہ کی چھٹی پالیسی',
  'settings.school.leave_policy.privilege_per_year': 'فی سال خصوصی چھٹیاں',
  'settings.school.leave_policy.sick_per_year': 'فی سال بیماری کی چھٹیاں',
  'settings.school.school_id_label': 'اسکول آئی ڈی',
  'settings.school.school_id_placeholder': 'منفرد اسکول آئی ڈی درج کریں (مثلاً، SCH001)',
  'settings.school.school_id_help': 'اسکول آئی ڈی صرف پہلی ترتیب کے دوران سیٹ کی جا سکتی ہے',
  'settings.school.school_name_label': 'اسکول کا نام',
  'settings.school.logo_url_label': 'لوگو URL',
  'settings.school.principal_name_label': 'پرنسپل کا نام (رسیدوں کے لیے)',
  'settings.school.example.principal_name': 'مثلاً، ڈاکٹر اے۔ بی۔ پرنسپل',
  'settings.school.principal_signature_label': 'پرنسپل دستخط',
  'settings.school.principal_signature_placeholder': 'دستخط کی تصویر کا URL',
  'settings.school.signature_uploaded': 'دستخط اپلوڈ ہو گیا',
  'settings.school.preview': 'پیش نظارہ:',
  'settings.school.contact.phone_label': 'فون',
  'settings.school.contact.email_label': 'ای میل',
  'settings.school.contact.website_label': 'ویب سائٹ',
  'settings.school.address.street_label': 'پتہ (گلی)',
  'settings.school.address.city_label': 'شہر',
  'settings.school.address.state_label': 'صوبہ',
  'settings.school.address.zip_label': 'زپ کوڈ',
  'settings.school.config.academic_year_label': 'اکیڈمک سال',
  'settings.school.config.grade_system_label': 'گریڈ سسٹم',
  'settings.school.config.currency_label': 'کرنسی',
  'settings.school.config.timezone_label': 'ٹائم زون',
  'settings.school.example.academic_year': 'مثلاً، 2025-2026',
  'settings.school.example.grade_system': 'مثلاً، فیصد',
  'settings.school.example.currency': 'مثلاً، INR',
  'settings.school.example.timezone': 'مثلاً، Asia/Kolkata',
  'settings.school.config.student_id_format_label': 'ڈیفالٹ طالب علم آئی ڈی فارمیٹ',
  'settings.school.example.student_id_format': 'مثلاً، STU-{YYYY}-{SEQ}',
  'settings.school.config.employee_id_format_label': 'ڈیفالٹ ملازم آئی ڈی فارمیٹ',
  'settings.school.example.employee_id_format': 'مثلاً، EMP-{YYYY}-{SEQ}',
  'error.upload_failed': 'اپلوڈ ناکام',

  // Parent Dashboard
  'parent.dashboard.title': 'والدین ڈیش بورڈ',
  'parent.dashboard.welcome': 'خوش آمدید، {name}! بچوں کی کارکردگی دیکھیں۔',
  'parent.dashboard.attendance': 'حاضری',
  'parent.dashboard.average_grade': 'اوسط گریڈ',
  'parent.dashboard.upcoming_exams': 'آئندہ امتحانات',
  'parent.dashboard.pending_fees': 'بقیہ فیس',
  'parent.dashboard.view_details': 'تفصیل دیکھیں',
  'parent.dashboard.recent_activities': 'تازہ سرگرمیاں',
  'parent.dashboard.no_recent_activities': 'کوئی تازہ سرگرمی نہیں',
  'parent.dashboard.pending_leave_approvals': 'زیر التواء چھٹی منظوری',
  'parent.dashboard.no_pending_requests': 'کوئی زیر التواء درخواست نہیں',
  'parent.dashboard.upcoming_events': 'آئندہ تقریبات',
  'parent.dashboard.no_upcoming_events': 'کوئی آئندہ تقریب نہیں',
  'parent.dashboard.children_performance_comparison': 'بچوں کی کارکردگی موازنہ',
  'parent.dashboard.reason_rejection_prompt': 'رد کرنے کی وجہ؟',
  'parent.dashboard.rejected_by_parent': 'والدین نے مسترد کیا',

  'error.fill_required_fields': 'براہ کرم تمام لازمی خانے پُر کریں',
  'error.failed_to_submit_leave': 'چھٹی کی درخواست جمع کرنے میں ناکامی',
  'error.failed_to_apply_leave': 'چھٹی کی درخواست دینے میں ناکامی',
  'error.failed_to_load_dashboard': 'ڈیش بورڈ لوڈ کرنے میں ناکامی',
  'error.failed_to_load_quizzes': 'کوئز لوڈ کرنے میں ناکامی',
  'error.failed_to_start_quiz': 'کوئز شروع کرنے میں ناکامی',
  'error.failed_to_load_results': 'نتائج لوڈ کرنے میں ناکامی',
  'error.failed_to_submit_quiz': 'کوئز جمع کرنے میں ناکامی',
  'error.failed_to_approve_leave': 'چھٹی منظور کرنے میں ناکامی',
  'error.failed_to_reject_leave': 'چھٹی مسترد کرنے میں ناکامی',
  'error.failed_to_fetch_class_stats': 'کلاس کے اعدادوشمار حاصل کرنے میں ناکامی',
  'error.failed_to_fetch_teacher_stats': 'استاد کے اعدادوشمار حاصل کرنے میں ناکامی',
  'error.failed_to_fetch_finance_summary': 'مالی خلاصہ حاصل کرنے میں ناکامی',
  'error.failed_to_load_children': 'بچوں کو لوڈ کرنے میں ناکامی',
  'error.failed_to_load_performance': 'کارکردگی لوڈ کرنے میں ناکامی',

  'time.just_now': 'ابھی',
  'time.mins_ago': '{mins} منٹ پہلے',
  'time.hours_ago': '{hours} گھنٹے پہلے',
  'time.days_ago': '{days} دن پہلے',

  // Navigation
  'nav.dashboard': 'ڈیش بورڈ',
  'nav.students': 'طلباء',
  'nav.teachers': 'اساتذہ',
  'nav.classes': 'کLASسز',
  'nav.subjects': 'مضامین',
  'nav.exams': 'امتحانات',
  'nav.fees': 'فیس',
  'nav.timetable': 'ٹائم ٹیبل',
  'nav.attendance': 'حاضری',
  'nav.notifications': 'اطلاعات',
  'nav.settings': 'سیٹنگز',
  'nav.my_children': 'میرے بچے',
  'nav.performance': 'کارکردگی',
  'nav.fee_payments': 'فیس ادائیگی',
  'nav.assignments': 'اسائنمنٹس',
  'nav.quizzes_tests': 'کوئز و ٹیسٹ',
  'nav.exams_results': 'امتحانات و نتائج',
  'nav.my_attendance': 'میری حاضری',
  'nav.fee_payment': 'فیس ادائیگی',
  'nav.my_classes': 'میری کلاسز',
  'nav.my_timetable': 'میرا ٹائم ٹیبل',
  'nav.study_materials': 'مطالعہ مواد',
  'nav.quiz_test': 'کوئز و ٹیسٹ',
  'nav.grading': 'گریڈنگ',
  'nav.teacher_students': 'طلباء',
  'nav.finance_tools': 'مالیاتی ٹولز',
  'nav.notification_tools': 'اطلاعی ٹولز',
  'nav.admin_reports': 'ایڈمن رپورٹس',

  'admin.reports.subtitle': 'کلاس، استاد اور مالی خلاصے (CSV) ڈاؤن لوڈ کریں۔ ایکسل/پی ڈی ایف جلد آرہے ہیں۔',
  'admin.reports.class_stats': 'کلاس وار اعدادوشمار',
  'admin.reports.teacher_report': 'استاد رپورٹ',
  'admin.reports.finance_summary': 'مالی خلاصہ',
  'admin.reports.select_class': 'کلاس منتخب کریں',
  'admin.reports.select_school': 'اسکول منتخب کریں',
  'admin.reports.teacher_id_placeholder': 'استاد ID',

  'parent.performance.rating.excellent': 'بہترین',
  'parent.performance.rating.good': 'اچھا',
  'parent.performance.rating.needs_attention': 'توجہ درکار ہے',

  'parent.performance.title': 'تعلیمی کارکردگی',
  'parent.performance.subtitle': 'اپنے بچوں کی کارکردگی دیکھیں',
  'parent.performance.select_child': 'بچے کا انتخاب کریں',
  'parent.performance.overall_average': 'مجموعی اوسط',
  'parent.performance.class_rank': 'کلاس درجہ',
  'parent.performance.progress': 'پیش رفت',
  'parent.performance.no_data': 'کوئی ڈیٹا دستیاب نہیں',
  'parent.performance.subject_wise': 'موضوع کے لحاظ سے کارکردگی',
  'parent.performance.assignments': 'اسائنمنٹس',
  'parent.performance.exams': 'امتحانی نتائج',
  'parent.performance.quizzes': 'کوئز و ٹیسٹ',
  'parent.performance.no_assignments': 'کوئی اسائنمنٹ نہیں ملا',
  'parent.performance.no_quizzes': 'کوئی کوئز/ٹیسٹ نہیں ملا',

  'table.title': 'عنوان',
  'table.subject': 'مضمون',
  'table.type': 'قسم',
  'table.status': 'حالت',
  'table.marks': 'نمبر',
  'table.percent': '%',
  'table.result': 'نتیجہ',
  'table.student': 'طالب علم',
  'table.class': 'کلاس',
  'table.submitted': 'جمع کیا گیا',
  'table.grade': 'گریڈ',
  'table.date': 'تاریخ',
  'table.quiz': 'کوئز',
  'table.exam': 'امتحان',

  'result.passed': 'کامیاب',
  'result.failed': 'ناکام',

  'student.quizzes.results': 'نتائج',
  'student.quizzes.attempt': 'کوشش',
  'student.quizzes.score': 'اسکور',
  'student.quizzes.status': 'حالت',
  'student.quizzes.submitted': 'جمع کیا',
  'student.quizzes.title': 'کوئز و ٹیسٹ',
  'student.quizzes.subtitle': 'اپنے آن لائن کوئز اور ٹیسٹ شروع کریں اور جمع کریں',
  'student.quizzes.type': 'قسم',
  'student.quizzes.due': 'واجب الادا',
  'student.quizzes.attempts': 'کوششیں',
  'student.quizzes.action': 'عمل',
  'student.quizzes.start': 'شروع کریں',
  'student.quizzes.reattempt': 'دوبارہ کوشش',
  'student.quizzes.view_results': 'نتائج دیکھیں',
  'student.quizzes.time_remaining': 'باقی وقت',
  'student.quizzes.cancel': 'منسوخ کریں',
  'student.quizzes.submit': 'جمع کریں',
  'student.quizzes.no_attempts': 'کوئی کوشش نہیں ملی۔',
  'student.quizzes.expired': 'یہ کوشش پہلے ہی ختم ہو چکی ہے۔ براہ کرم دوبارہ شروع کریں۔',
  'student.quizzes.mcq': 'MCQ',
  'student.quizzes.scq': 'SCQ',
  'student.quizzes.submitted_label': 'جمع ہو گیا۔',
  'student.quizzes.score_label': 'اسکور',
  'student.quizzes.option': 'آپشن {n}',
  'student.quizzes.q_prefix': 'سوال ',
  'student.quizzes.question_image': 'سوال کی تصویر',
  'student.quizzes.your_best': 'آپ کا بہترین',
  'student.quizzes.rank_of': 'درجہ #{rank} میں سے {participants}',
  'student.quizzes.avg': 'اوسط {avg}%',
  'student.quizzes.top': 'سرفہرست {top}%',
};

const dicts: Record<Lang, Dict> = { en, hi, ur };

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  dir: 'ltr' | 'rtl';
  t: (key: string) => string;
};

const LangContext = createContext<Ctx | undefined>(undefined);

export const LangProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = (typeof window !== 'undefined' ? localStorage.getItem('lang') : null) as Lang | null;
    return saved || 'en';
  });

  useEffect(() => {
    try { localStorage.setItem('lang', lang); } catch {}
    try {
      const el = document.documentElement;
      el.setAttribute('lang', lang);
      el.setAttribute('dir', lang === 'ur' ? 'rtl' : 'ltr');
    } catch {}
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);
  const dir: 'ltr' | 'rtl' = lang === 'ur' ? 'rtl' : 'ltr';

  const t = useMemo(() => {
    return (key: string) => {
      const d = dicts[lang] || en;
      return d[key] ?? en[key] ?? key;
    };
  }, [lang]);

  const value: Ctx = { lang, setLang, dir, t };
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
